font_family family="Source Code Pro"
font_size 11.0

detect_urls yes
allow_hyperlinks no

remember_window_size yes
remember_window_position yes

update_check_interval 0

background_opacity 0.8

# This is set to be slightly unequal to color0.
background #1c1e20
foreground #c5c8c6
color0 #1d1f21
color1 #cc6666
color2 #b5bd68
color3 #f0c674
color4 #81a2be
color5 #b294bb
color6 #8abeb7
color7 #c5c8c6
color8 #666666
color9 #d54e53
color10 #b9ca4a
color11 #e7c547
color12 #7aa6da
color13 #c397d8
color14 #70c0b1
color15 #eaeaea

close_on_child_death yes

clipboard_control none

map ctrl+shift+f5 load_config_file
map cmd+u open_url_with_hints
map ctrl+cmd+s save_as_session --use-foreground-process --base-dir ~/.local/state/kitty/sessions

enable_audio_bell no
command_on_bell dct-sound --beep

startup_session ~/.local/state/kitty/sessions/default

term kitty
