#!/usr/bin/env ruby

require 'optparse'
require 'yaml'

class DesktopConfigProcessor
  class BaseDesktopConfigProcessor
    attr_reader :config, :options

    def process
      config[top_section].each do |(cfg, cfgdata)|
        cfgdata[entry_section].each do |(group, groupdata)|
          groupdata.each do |(key, value)|
            process_config(options, cfg, [group], key, value)
          end
        end
      end
    end

    def process_config(options, cfg, groups, key, value)
      if value.is_a?(Hash)
        groups = groups.dup
        groups << key
        value.each do |(key, val)|
          process_config(options, cfg, groups, key, val)
        end
      else
        run_command(format_args(cfg, groups, key, value))
      end
    end

    protected

    def run_command(args)
      $stderr.puts "Running #{command} #{args.join(" ")}" if options[:verbose]
      unless options[:dry_run]
        spawn(options[:env], command, *args)
        Process.wait
      end
    end
  end

  class KDEDesktopConfigProcessor < BaseDesktopConfigProcessor
    def initialize(config, options)
      @config = config
      @options = options
    end

    def top_section
      'files'
    end

    def entry_section
      'groups'
    end

    def command
      'kwriteconfig6'
    end

    def format_args(cfg, groups, key, value)
      file = File.join(options[:base], cfg)
      args = ["--file", file]
      args += groups.flat_map { |g| ["--group", g] }
      args += ["--key", key.to_s]
      case value
      when [true, false]
        args += ["--type=bool", value.to_s]
      when nil
        args += ["--delete"]
      else
        args += [value.to_s]
      end
    end
  end

  def initialize(stdin, stdout, stderr)
    @stdin = stdin
    @stdout = stdout
    @stderr = stderr
  end

  def process_file(options, file)
    data = YAML.safe_load(File.read(file))
    p = KDEDesktopConfigProcessor.new(data, options)
    p.process
  end

  def run(env, args)
    env = env.to_h
    base = env["XDG_CONFIG_HOME"] || File.join(env["HOME"], ".config")
    options = {files: [], base: base, env: env}
    OptionParser.new do |opts|
      opts.on("-f", "--file FILE", "process FILE") do |arg|
        options[:files] << arg
      end

      opts.on("-v", "--verbose", "be more verbose") do
        options[:verbose] = true
      end

      opts.on("-n", "--dry-run", "just print what would be done, don't do it") do
        options[:dry_run] = true
      end
    end.order!(args)

    options[:files].each do |file|
      process_file(options, file)
    end
    0
  end
end

exit DesktopConfigProcessor.new($stdin, $stdout, $stderr).run(ENV, ARGV) if __FILE__ == $0
