#!/bin/sh

URL=$(formail -c -X List-Unsubscribe | ruby -ne '
    if $_ =~ %r[^(?i:List-Unsubscribe):(.*)]
        line = $1
        line.gsub!(/=\?(?:utf-8|us-ascii|iso-8859-\d+)\?([qb])\?(\S+)\?=(\s+|$)/i) do |m|
            case $1
            when "q", "Q"
                $2.gsub("_", "\x20").unpack("M")[0]
            when "b", "B"
                $2.unpack("m")[0]
            end
        end
        puts $1 if line =~ %r[^.*<(https?://[^>]+)>.*$];
    end')

if [ -n "$URL" ]
then
    printf 'Unsubscribing via %s\n' "$URL"
    curl -X POST -H'Content-Type: application/x-www-form-urlencoded' -dList-Unsubscribe=One-Click "$URL"
else
    printf 'No URL found.' >&2
    exit 1
fi

if [ "$1" = "--wait" ]
then
    read -r dummy </dev/tty
fi
