#!/bin/zsh

# Print a prompt code (valid for print -P) that sets the appropriate foreground
# color.  The color can be a name that zsh understands or a numerical value
# appropriate for the terminal.
color_bg () {
    local color="$1"

    [[ $TERM = dumb ]] && return 0

    printf "%%{%%K{%s}%%}" $color
}
