# brian m. carlson's zlogout file.
# Used for logging out.


# Clear the screen, so evil people cannot see what we were doing, but only on a
# real TTY.
if tty 2>/dev/null | grep -qsv pts
then
    clear
fi
