#!/bin/zsh

source "$HOME/.zshenv"

if [ -z "${ZSH_ARGZERO##/*zsh}" ]
then
    export SHELL="$ZSH_ARGZERO"
elif [ -z "${ZSH_ARGZERO##-/*zsh}" ]
then
    export SHELL="${ZSH_ARGZERO##-}"
elif command -v "$ZSH_NAME" >/dev/null 2>&1
then
    export SHELL="$(command -v "$ZSH_NAME" 2>/dev/null)"
fi
