# brian m. carlson's zshenv.

# Useful functions used in this file.  General definitions go in .zshrc.
dct-has-locale () {
    local locale="$1"

    [ -x "$(command -v perl)" ] || return 0
    perl -MPOSIX=locale_h -E 'exit !setlocale(LC_ALL, $ARGV[0]);' "$locale" \
        2>/dev/null
}

dct-preferred-locale () {
    local locale=$(sed -e 's/.utf8$/.UTF-8/' <<<"$LANG")
    # If we're using English, prefer Canadian English; otherwise, accept English,
    # Spanish, or French locales.  Otherwise, fall back to US English.
    if [[ -z ${locale##en*.UTF-8} ]] && dct-has-locale 'en_CA.UTF-8'; then
        printf "en_CA.UTF-8"
        return 0
    elif [[ -z ${locale##(en|es|fr)*.UTF-8} ]]; then
        printf '%s' "$locale"
        return 0
    fi
    printf "en_US.UTF-8"
}

dct-is-ssh-session () {
    [[ -n $SSH_CLIENT ]] || [[ -n $SSH_CONNECTION ]] || [[ -n $SSH_TTY ]]
}

# Return true if our home directory is owned by someone other than us.
dct-is-privileged () {
    zmodload -F zsh/stat b:zstat
    [ "$(zstat -L +uid "$HOME")" -ne "$(id -u)" ]
}

dct-has-display () {
    [ -n "$DISPLAY" ] || [ -n "$WAYLAND_DISPLAY" ] || [ "$(launchctl managername 2>/dev/null)" = Aqua ] ||
        ([ "$(uname -s)" = Darwin ] && [ -z "$REMOTE_ENV" ])
}

dct-set-up-xdg-vars () {
    local i

    if [ -z "$XDG_RUNTIME_DIR" ]
    then
        zmodload -F zsh/stat b:zstat
        for i in "/run/user/$(id -u)" \
            "/var/run/user/$(id -u)"
        do
            if [ -d "$i" ] && [ "$(zstat -L +uid "$HOME")" -eq "$(id -u)" ]
            then
                export XDG_RUNTIME_DIR="$i"
                break
            fi
        done
    fi

    if [ -z "$XDG_STATE_DIR" ]
    then
        for i in "$HOME/mnt/remote/state" \
            "$HOME/.local/state"
        do
            if [ -d "$i" ]
            then
                export XDG_STATE_DIR="$i"
                break
            fi
        done
    fi
}

dct-set-up-ssh-agent () {
    local i
    dct-is-ssh-session && return
    dct-is-privileged && return
    for i in "$HOME/.1password/agent.sock"
    do
        if [[ -S "$i" ]]
        then
            export SSH_AUTH_SOCK="$i"
            return
        fi
    done
    grep enable-ssh-support ~/.gnupg/gpg-agent.conf 2>/dev/null | \
        grep -qsv '^#' || return
    gpg-connect-agent /bye >/dev/null 2>&1
    for i in "$(gpgconf --list-dirs | grep '^agent-socket:' | cut -d: -f2)" \
        "$HOME/.gnupg/S.gpg-agent" \
        "/run/user/$(id -u)/gnupg/S.gpg-agent"
    do
        [[ -S "$i.ssh" ]] && export SSH_AUTH_SOCK="$i.ssh"
    done
}

dct-set-up-temp () {
    local i
    for i in "$TMPDIR" "$TEMPDIR" "$TMP" "$TEMP" "/tmp"
    do
        if [[ -n $i ]]
        then
            # Remove trailing slash.
            i=$(sed -e 's,/*$,,' <<<"$i")

            # This is the POSIX variable.
            export TMPDIR="$i"
            export TEMPDIR="$i"
            # This is the short, easy-to-type variable.
            export TMP="$i"
            export TEMP="$i"
            return
        fi
    done
}

dct-editor () {
    local console=a dumb=a display=n detach=a fallback=t remote=n

    while [[ -n $1 ]]
    do
        case "$1" in
            --console)
                console=t;;
            --dumb)
                dumb=t;;
            --detach)
                detach=t;;
            --fallback)
                fallback=t;;
            --no-fallback)
                fallback="";;
        esac
        shift
    done

    dct-has-display && display=t
    [[ $TERM = dumb ]] && dumb=t
    [[ -n $REMOTE_ENV ]] && remote=t

    local wanted=":detach=${detach}:console=${console}:dumb=${dumb}:display=${display}:remote=${remote}:"

    awk -F: "wanted = \"${wanted}\""'
        gsub("=t:", "=[ta]:", wanted)
        gsub("=n:", "=[na]:", wanted)
        gsub("=a:", "=[tna]:", wanted)
        pattern = "^[^#].*" wanted "$"
        $0 ~ pattern { printf("%s %s\n", $1, $2) }' "$HOME/.config/zsh/editors" | \
        while read -r line
        do
            local cmd="${line%% *}"
            if command -v "$cmd" >/dev/null 2>&1
            then
                printf '%s' "$line"
                return
            fi
        done

    [[ -n $fallback ]] && printf 'vi'
}

dct-source-if-present () {
    local fn="$1"
    [[ -f $fn ]] && source "$fn"
}

dct-set-up-path-hook () {
}

dct-set-up-path_components () {
    local name
    for name in "$@"
    do
        eval "for i in \$${name}path
        do
            components+=([\$i]=$name)
        done"
    done
}

dct-append-paths () {
    local name
    for name in "$@"
    do
        if [[ -z $chosen[$name] ]]
        then
            eval "path+=(\$${name}path)"
            chosen+=([$name]=t)
        fi
    done
}

dct-set-up-path () {
    setopt localoptions shwordsplit

    local prevpath="$PATH"
    typeset -UT COREPATH corepath
    typeset -U personalpath
    typeset -U softwarepath
    typeset -U localpath
    typeset -U expansionpath
    typeset -xU manpath MANPATH
    local i

    [[ -n $BMC_TEST ]] && return

    unset CDPATH

    personalpath=(
        ~/bin
        ~/.local/bin
    )
    softwarepath=(
        ~/.rvm/bin
        ~/.cargo/bin
    )
    localpath=(
        /usr/local/bin
        /usr/local/sbin
    )
    expansionpath=(
        /opt/homebrew/bin
        /opt/homebrew/sbin
    )
    corepath=(
        /usr/bin
        /usr/sbin
        /bin
        /sbin
        /usr/games
    )

    MANPATH="$HOME/.local/share/man:"

    dct-set-up-path-hook

    typeset -A components chosen
    typeset -xU path
    typeset -xU PATH

    dct-set-up-path_components personal software local core

    path=($personalpath)
    chosen+=([personal]=t)

    for i in $(echo "$prevpath" | PATH="$COREPATH" tr : '\n')
    do
        case "$components[$i]" in
            personal)
                ;;
            software)
                dct-append-paths software
                ;;
            local)
                dct-append-paths software local
                ;;
            expansion)
                dct-append-paths software local expansion
                ;;
            core)
                dct-append-paths software local expansion core
                ;;
            *)
                path+=($i)
                ;;
        esac
    done

    dct-append-paths software local expansion core

    # Export miscellaneous paths.
    export MANPATH PATH COREPATH
}

# Set options.
setopt shwordsplit
setopt rmstarsilent
unsetopt bgnice
unsetopt equals
unsetopt nomatch

# Set up some limits.
unlimit
limit | grep -qs core && limit core 0

# Set up umask.  If we have private groups, use 002; otherwise, use 022.
if [[ $(id -u -n) = $(id -g -n) ]]; then
    umask 002
else
    umask 022
fi

if [[ -z $BMC_TEST ]]
then
    # Nuke dupes.
    typeset -U fpath
    typeset -xU FPATH
    fpath+=(~/.config/zsh/functions ~/.config/zsh/completion)
fi

local the_preferred_locale=$(dct-preferred-locale)

# Set other variables.
setopt allexport

if [[ -z $TERM ]] && ! tty >/dev/null 2>&1
then
    TERM=dumb
fi

if [[ ! -d "$HOME/.rvm" ]] && command -v ruby >/dev/null 2>&1
then
    ver="$(ruby -e 'puts RUBY_VERSION')"
    if [[ -z $GEM_HOME ]]
    then
        GEM_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/gems/$ver"
    fi
    unset ver
fi

if [[ -n "$CODESPACES" ]]; then
    REMOTE_ENV=codespaces
elif dct-is-ssh-session; then
    REMOTE_ENV=ssh
fi

LANG="$the_preferred_locale"
LC_ADDRESS=en_CA.UTF-8
LC_COLLATE="$the_preferred_locale"
LC_CTYPE=en_CA.UTF-8
LC_IDENTIFICATION="$the_preferred_locale"
LC_MONETARY=en_CA.UTF-8
LC_MEASUREMENT=POSIX
LC_MESSAGES="$the_preferred_locale"
LC_NAME="$the_preferred_locale"
LC_NUMERIC=en_CA.UTF-8
LC_PAPER=en_CA.UTF-8
LC_TIME=POSIX
LC_TELEPHONE=en_CA.UTF-8
TZ=UTC

GIT_PAGER="less -FRSX"
PAGER="less -R"
PERLDOC_PAGER="$PAGER"
LESS="-fR"
EDITOR=$(dct-editor --dumb)
VISUAL=$(dct-editor)
GIT_MERGE_AUTOEDIT=no
XML_CATALOG_FILES="$HOME/.crustytoothpaste/groups/metadata/xml-catalogs/catalog.xml"
MODULE_SIGNATURE_CIPHER=SHA512
# Don't use weird escapes in ls.
QUOTING_STYLE=literal
GOPATH="$HOME/checkouts/go"
GOPROXY=direct
GOTOOLCHAIN=local
BROWSER=dct-browser
DO_NOT_TRACK=1
WINIT_X11_SCALE_FACTOR=1

if [[ ! -e "$XML_CATALOG_FILES" ]]; then
    unset XML_CATALOG_FILES
fi
if [[ -z $HOSTNAME ]]; then
    HOSTNAME=$(hostname)
fi
if dct-has-locale en_DK.UTF-8; then
    LC_TIME=en_DK.UTF-8
fi
if [ -f /etc/os-release ] && (( ${${(@f)"$(</etc/os-release)"}[(I)ID*=*ubuntu]} ))
then
    skip_global_compinit=1
fi

unsetopt allexport
# End exporting variables.

dct-set-up-xdg-vars
dct-set-up-ssh-agent
dct-set-up-temp
dct-source-if-present "$HOME/.rvm/scripts/rvm"
dct-source-if-present "$HOME/.config/zsh/zshenvlocal"
dct-set-up-path

unfunction dct-is-privileged
unfunction dct-has-locale
unfunction dct-preferred-locale
unfunction dct-set-up-xdg-vars
unfunction dct-set-up-ssh-agent
unfunction dct-set-up-temp
unfunction dct-set-up-path
unfunction dct-set-up-path-hook
unfunction dct-append-paths
unfunction dct-set-up-path_components

unset the_preferred_locale
true
