---
- name: Deploy dotfiles and configuration
  hosts: all
  environment:
    DEBIAN_FRONTEND: noninteractive
  vars:
    checkouts_dir: /home/{{ ansible_user_id }}/checkouts
    branch: dev
  tasks:
    - name: Create the directory
      file:
        path: '{{ checkouts_dir }}'
        state: directory
        owner: '{{ ansible_user_id }}'
        group: '{{ ansible_user_id }}'
    - name: Clone dotfiles
      git:
        repo: https://github.com/bk2204/dotfiles.git
        remote: def
        dest: '{{ checkouts_dir }}/dotfiles'
        version: '{{ branch }}'
    - name: Checkout submodules for dotfiles
      shell: 'git submodule update --init'
      args:
        chdir: '{{ checkouts_dir }}/dotfiles'
    - name: Deploy dotfiles with make
      shell: 'make install'
      args:
        chdir: '{{ checkouts_dir }}/dotfiles'
      when: ansible_distribution != 'FreeBSD'
    - name: Deploy dotfiles with gmake
      shell: 'gmake install'
      args:
        chdir: '{{ checkouts_dir }}/dotfiles'
      when: ansible_distribution == 'FreeBSD'
    - name: Create .local directory
      file:
        path: '/home/{{ ansible_user_id }}/.local'
        state: directory
    - name: Create .local/run directory
      file:
        path: '/home/{{ ansible_user_id }}/.local/run'
        state: directory
    - name: Create Lawn directory
      file:
        path: '/home/{{ ansible_user_id }}/.local/run/lawn'
        state: directory
