---
- name: Deploy dotfiles and configuration
  hosts: all
  environment:
    DEBIAN_FRONTEND: noninteractive
  vars:
    checkouts_dir: '{{ ansible_facts["user_dir"] }}/checkouts'
    branch: dev
    font_srcs:
      /usr/share/texlive/texmf-dist/fonts/opentype: texlive-opentype
      /usr/share/texlive/texmf-dist/fonts/truetype: texlive-truetype
    group: '{{ ansible_facts["user_id"] }}'
    dotfiles_config: 'config/config-dev.yaml'
    private_dotfiles: true
  tasks:
    - name: Create the directory
      file:
        path: '{{ checkouts_dir }}'
        state: directory
        owner: '{{ ansible_facts["user_id"] }}'
        group: '{{ group }}'
    - name: Clone dotfiles
      git:
        repo: https://github.com/bk2204/dotfiles.git
        remote: def
        dest: '{{ checkouts_dir }}/dotfiles'
        version: '{{ branch }}'
    - name: Determine config
      stat:
        path: '{{ checkouts_dir }}/dotfiles/config.yaml'
        follow: false
      register: config
    - name: Set default config
      file:
        src: '{{ dotfiles_config }}'
        dest: '{{ checkouts_dir }}/dotfiles/config.yaml'
        owner: '{{ ansible_facts["user_id"] }}'
        group: '{{ group }}'
        state: link
      when: config.stat.exists is defined and not config.stat.exists
    - name: Checkout submodules for dotfiles
      shell: 'git submodule update --init'
      args:
        chdir: '{{ checkouts_dir }}/dotfiles'
    - name: Deploy dotfiles with make
      shell: 'make install'
      args:
        chdir: '{{ checkouts_dir }}/dotfiles'
      when: ansible_facts["distribution"] not in ["FreeBSD", "Darwin"]
    - name: Deploy dotfiles with gmake
      shell: 'gmake install'
      args:
        chdir: '{{ checkouts_dir }}/dotfiles'
      when: ansible_facts["distribution"] in ["FreeBSD", "Darwin"]
    # This happens after the initial deployment because we need the ssh config
    # to set VerifyHostKeyDNS for us.
    - name: Clone dotfiles-private
      git:
        repo: ssh://git@git.crustytoothpaste.net/bmc/dotfiles-private.git
        remote: def
        dest: '{{ checkouts_dir }}/dotfiles-private'
        version: '{{ branch }}'
      when: private_dotfiles
    - name: Re-deploy dotfiles with make
      shell: 'make install'
      args:
        chdir: '{{ checkouts_dir }}/dotfiles'
      when: ansible_facts["distribution"] not in ["FreeBSD", "Darwin"]
    - name: Re-deploy dotfiles with gmake
      shell: 'gmake install'
      args:
        chdir: '{{ checkouts_dir }}/dotfiles'
      when: ansible_facts["distribution"] in ["FreeBSD", "Darwin"]
    - name: Create .local directory
      file:
        path: '{{ ansible_facts["user_dir"] }}/.local'
        state: directory
    - name: Create .local/share directory
      file:
        path: '{{ ansible_facts["user_dir"] }}/.local/share'
        state: directory
    - name: Create .local/run directory
      file:
        path: '{{ ansible_facts["user_dir"] }}/.local/run'
        state: directory
    - name: Create Lawn directory
      file:
        path: '{{ ansible_facts["user_dir"] }}/.local/run/lawn'
        state: directory
    - name: Create fonts directory
      file:
        path: '{{ ansible_facts["user_dir"] }}/.local/share/fonts'
        state: directory
    - name: Set up fonts
      include_tasks: "{{ playbook_dir }}/deploy-dotfiles-fonts.yaml"
      loop: "{{ font_srcs | dict2items }}"
    - name: Regenerate font cache
      shell: fc-cache
      when: fonts.stat.exists and fonts.stat.isdir
