---
- name: 'Check for {{ item.repository }} keyring'
  stat:
    path: '{{ item.keyring }}'
    get_checksum: false
    get_mime: false
  register: keyring
- name: 'Download {{ item.repository }} keyring'
  get_url:
    dest: '{{ item.downloaded_keyring }}'
    mode: '0644'
    owner: root
    group: root
    url: '{{ item.remote_keyring }}'
    use_netrc: false
  become: true
  become_user: root
  when: item.condition and not keyring.stat.exists
- name: 'Dearmor {{ item.repository }} keyring'
  command: 'gpg --dearmor --output {{ item.keyring }} {{ item.downloaded_keyring }}'
  become: true
  become_user: root
  when: item.condition and not keyring.stat.exists and item.downloaded_keyring != item.keyring
- name: 'Set up {{ item.repository }} sources.list entry'
  copy:
    src: '{{ playbook_dir }}/files{{ item.sources_list_path }}'
    dest: '{{ item.sources_list_path }}'
    owner: root
    group: root
    mode: "644"
  become: true
  become_user: root
  when: item.condition
- name: 'Install {{ item.repository }}'
  apt:
    pkg: '{{ item.packages }}'
    update_cache: true
  become: true
  become_user: root
  when: item.condition and item.packages != None
